{
 "title": "SMU stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SMU resource stats",
   "type": "bargauge",
   "description": "SMU resource usage statistics display",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "smu_res_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Node packet stats",
   "type": "graph",
   "description": "Packet statistics of PFCP node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "smu_node_detail", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "SMU  N4 packet stats",
   "type": "graph",
   "description": "N4 packet statistics of SMU",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "smu_pkt_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Session packet stats",
   "type": "graph",
   "description": "Packet statistics of PFCP session ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "smu_sess_detail", "legendFormat": "{{name}}" }
   ]
  }
 ]
}